### ISSUE TITLE
imagelayereffect

### ISSUE THREAD

**Issue by vl25** [zhdanovartur/yii-easyimage#40]
Hallo, i have one problem with watermark!

i am use this

> Yii::app()->easyImage->thumbSrcOf($_SERVER['DOCUMENT_ROOT'] . Yii::app()->params['portfolioImgDir'] . $img->filename,
                            [
                                'resize' => ['width' => 1024, 'height' => 768],
                                'type' => 'jpg',
                                'watermark' => ['watermark' => '/images/watermark.png', 'opacity' => 50],
                            ])

but i have problem with gd, in config allow only quality

> This method requires imagelayereffect, which is only available in the bundled version of GD

**Comment by zhdanovartur** [comment]
Hi, try using Imagic:
```
apt-get update
apt-get install imagemagic
apt-get install php5-imagick
```
and in `easyImage` section set `drive`r as `Imagic`:

**Comment by vl25** [comment]
thanks, and now new problem)))

wtf?

> include(Image_Imagic.php): failed to open stream: No such file or directory

**Comment by vl25** [comment]
it's worked!!!!! thank you!!
